name: flame_audio
description: Audio support for the Flame game engine. This containst all audio related code will live in the future, using the audioplayers package.
version: 1.0.2
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_audio

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flame:
    path: ../flame
  audioplayers: ^1.0.0-rc.4
  synchronized: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  dartdoc: ^4.1.0
  flame_lint: ^0.0.1
